import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css' 

import {Toaster} from 'react-hot-toast'
import {Providers} from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body >
        <Providers>
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </Providers>
      </body>
    </html>
  )
}
